config/routes.rb
Rails.application.routes.draw do

  resources :session, only: [:new, :create, :destroy]
  root "posts#index"
  resources :posts do
    resources :comments
  end
  resources :users, only: [:new, :create]

  get "/picture", to: "posts#picture"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :post
  validates :commenter, presence: true
  validates :body, presence: true, length: {minimum: 10}

end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ["public", "private", "archived" ]

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end


  class_methods do
    def public_count
      where(status: "public").count
    end

    def private_count
      where(status: "private").count
    end
  end
  def archived?
    status == "archived"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include Visible
  include ShowPosts

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 10}


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true , length: { minimum: 3, maximum: 50 }
  validates :email, presence: true , length: { minimum: 3, maximum: 50 }
  validates :nickname, presence: true , length: { minimum: 3, maximum: 50 }
  # validates :password, presence: true , length: { minimum: 3, maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private
  def current_user
    Rails.logger.info "sessssssssss#{session[:id].inspect}" if session[:user_id].present?
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
    Rails.logger.info "------------------user-------------- #{@current_user.inspect}"
    @current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # http_basic_authenticate_with name: 'name', password: 'secret', only: :destroy

  before_action :set_post, only: %i[destroy create]
  def create
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post), status: :see_other
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # http_basic_authenticate_with  name: 'serg', password: 'secret', except: [:index, :show]

  before_action :set_post, only: [:show, :edit, :update, :destroy]

    def index
      @posts = Post.all
      case params[:state]
        when "first post"
          post = Post.first
          @posts = post ? [post] : []
      when "last post"
          post = Post.last
          @posts = post ? [post] : []
      else
        @posts = Post.all
      end
    end

  def show
    show_log params
  end

  def new
    @post = Post.new
  end

  def picture
    @post = params[:id]
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
    flash[:notice] = "You post is created"
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, status: :see_other
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :status)
  end

  def set_post
    @post = Post.find(params[ :id])
  end

  def show_log value
    Rails.logger.info "*********#{value}**********"
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session).permit(:email, :password)
    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])
    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in!"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    Rails.logger.info "-------------------------------- #{@current_user.inspect}"

    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:name, :nickname, :email, :password)
    @user = User.new(user_params)
    @session = session.to_hash
    if @user.save
      redirect_to root_path , notice: "Thanks for signing up!"
    else
      render :new, status: :unprocessable_entity
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_helper
    comments = Comment.all
    comments.count
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def log
    'helper test'
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
  <%  unless comment.archived? %>
    <div style="display: flex; justify-content: center">
      <div style="background-color: burlywood; width: 30%; border: solid black 5px; margin: 8px">
          <div style="margin: 5px">
            <h5 style="margin: 1px">Commenter: </h5>
            <strong><%= comment.commenter %></strong>
              <hr>
            <strong><%= comment.body %></strong>
              <%= l(comment.created_at, format: :short) %>
            <% if current_user.present? %>
            <p>
              <%= link_to "Delete comment", [comment.post, comment], data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %>
            </p>
              <% end %>
        </div>
    </div></div>
  <% end %>

app/views/comments/_form.html.erb
<div style="display: flex; justify-content: center; margin: 5px">
  <%= form_with model: [@post, @post.comments.build] do |form|  %>
      <p>
        <%= form.label :commenter  %> <br>
        <%= form.text_field :commenter %>
      </p>
      <p>
        <%= form.label :body  %> <br>
        <%= form.text_area :body %>
      </p>
      <div style="margin: 6px">
        <%= form.label :status %>
        <%= form.select :status, Visible::VALID_STATUSES, selected: post.status || "public" %>
      </div>
      <!--    <%#= form.submit %> //or-->
      <button type="submit">Add commentar</button>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-color: #DADADA">
  <div style=" padding: 20px; background-color: burlywood">
    <nav style="text-align: center">
      <% if current_user.present? %>
          <span style="align-self: start">Hi, <%= current_user.nickname %></span>
        <%= link_to "Create new post", new_post_path %>
        <%= link_to "Log out", new_session_path, data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>
      <% else %>
        <%= link_to 'Login', new_session_path %>
        <%= link_to "Registration", new_user_path %>
      <% end %>
        <%= link_to "Home", root_path %>

    </nav>



  </div>
  <hr>
    <% if flash[:notice].present? %>
      <p style="border: #730E15; background-color: burlywood; color: #730E15"><%= flash[:notice] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
  <%= form_with model: post do |form| %>
    <div style="border: #730E15 2px solid; width: fit-content">
      <div>
        <%= form.label :title %> <br>
        <%= form.text_field :title %>
        <% post.errors.full_messages_for(:title).each do |msg| %>
          <div>
            <%= msg %>
          </div>
        <% end %>
      </div>

      <div>
        <%= form.label :body %> <br>
        <%= form.text_area :body %>

        <% post.errors.full_messages_for(:body).each do |msg| %>
          <div>
            <%= msg %>
          </div>
        <% end %>
      </div>

      <div style="margin: 6px">
        <%= form.label :status %>
        <%= form.select :status, Visible::VALID_STATUSES, selected: post.status || "public" %>
      </div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/posts/_pic.html.erb
<h1> Partitiall template  <%=variable %> </h1>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<div style="text-align: start" class="wrapper">

<div>
  <div style=" margin: 5px; ">
    Our blog has <%= User.count %> users:
    <% User.all.each do |user| %>
      <span style="font-style: italic"><%= user.nickname %>, </span>
    <% end %> and <%= Post.public_count %> posts
  </div>

  <h1>Posts</h1>

  <div>
    <ul style="display: flex; flex-direction: column; align-content: center">
      <div>
        <p> Sorting</p>
        <%= form_with url: posts_path, method: :get, local: true do %>
          <%= select_tag :state, options_for_select(ShowPosts::SHOW_STATS) %>
          <%= submit_tag 'sort' %>
        <% end %>

      </div>
      <br>
    <% @posts.each do |post|  %>
        <% unless post.archived? %>
          <div style="border: #730E15 2px solid; border-radius: 50px; background-color: antiquewhite; margin: 5px">
            <%=  link_to post.title, post %>
            <p><%= post.body %></p>
            <i> writed: </i>
            <i> <%= l(post.created_at, format: :short) %></i>
          </div>
        <% end %>
      <% end %>

    </ul>
  </div>

</div>

</div>

app/views/posts/new.html.erb
<div style="margin:0 auto">

    <h1> Create new post</h1>

  <div style="display: flex; justify-content: center; margin: 10px">
    <%= render "form", post: @post %>
  </div>
</div>

app/views/posts/picture.html.erb
<h1> Pictures for post </h1>

<h2>Picture page <%=@post %></h2>

<%= render "pic", variable: @post%>

app/views/posts/show.html.erb
<div >
  <div style="display: flex; justify-content: center; text-align: center; border: #730E15 solid 9px;">
    <h1><%= @post.title %></h1>
    <hr>
    <p><%= @post.body %></p>
  </div>
  <div>
    <% if current_user.present? %>
    <ul>
      <li>
        <%= link_to "Edit post", edit_post_path(@post) %>
      </li>
      <li>
        <%= link_to "Delete", post_path(@post), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>
      </li>
    </ul>
      <% end %>
  </div>
    <div>
    <h5>
      We have:
        <%= comment_helper %>
      comments
    </h5>
      <div>
        <h3 style="">Comments:</h3>
        <p><%= render @post.comments %></p>
      </div>
    </div>
<div>
</div>
</div>

<div>
  <% if current_user.present? %>
  <h4> Add new comment:</h4>
  <div style="border: #2E2F30 2px solid; padding: 5px; background-color: beige">
    <%= render 'comments/form', post: @post %>
  </div>
    <% end %>
</div>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/new.html.erb
  <div style="display: flex; justify-content: center">

    <div style="border: #730E15 solid 2px; margin: 10px; width: fit-content">
  <h1>Login</h1>

  <% if flash[:notice] %>
    <p><%=flash[:alert] %></p>
  <% end %>
  <% if flash[:alert].present? %>
    <p style="border: #730E15 solid 3px"><%=flash[:alert] %></p>
  <% end %>

  <div style="display: flex; justify-content: center; gap: 20px">
    <%= form_with scope: :session,  url: session_index_path, data: {turbo: false}  do |f| %>
      <div style="margin: 10px">
        <%= f.label :email %>
        <%= f.email_field :email %>
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>

      <p style="margin: 10px">
       <%=  f.submit "Login" %>
      </p>
    <% end %>
  </div>
    </div>
</div>

app/views/users/_error_msg.html.erb
<% user.errors.full_messages_for(for_prop).each do |msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>

app/views/users/new.html.erb
<div style="display: flex; justify-content: center">

<div style="border: #730E15 solid 2px; margin: 10px; width: fit-content">
  <h1>Create new user</h1>
  <%= form_with model: @user do |form|%>
    <div style="margin:10px " >
        <span>
    <%= form.label :name, "Your name" %>
          <%= form.text_field :name%>
          <%= render "error_msg", user: @user, for_prop: :name %>
  </span>
      <span>
      <%= form.label :nickname, "Your nick" %>
        <%= form.text_field :nickname%>
        <%= render "error_msg", user: @user, for_prop: :nickname %>
    </span>
    </div>
    <p>
      <%= form.label :email, "Your email" %>
      <%= form.text_field :email%>
    </p>
    <%= render "error_msg", user: @user, for_prop: :email %>

    <p>
      <%= form.label :password, "Your password" %>
      <%= form.text_field :password%>
    </p>
    <%= render "error_msg", user: @user, for_prop: :password %>
  <button type="submit"> Register </button>
  <% end %>

</div>
</div>